[build]
  base = "/"
  command = "npx turbo build --filter=marketing"
  publish = "apps/marketing/.next"

[build.environment]
  NX_DAEMON = "false"
  TURBO_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_DEBUG_CACHE = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
