[build]
  # Build settings now managed in the Netlify UI to support multiple subdomains

[build.environment]
  NX_DAEMON = "false"
  TURBO_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_DEBUG_CACHE = "1"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
